// <auto-generated />
using System;
using Faucet.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Faucet.API.Migrations
{
    [DbContext(typeof(FaucetDbContext))]
    [Migration("20210523145017_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.6");

            modelBuilder.Entity("Faucet.API.Data.Balance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("BitcoinsCount")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Balance");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BitcoinsCount = 0m,
                            UpdatedAt = new DateTime(2021, 5, 23, 14, 50, 17, 114, DateTimeKind.Utc).AddTicks(6950)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
